### ISSUE TITLE
logging it doesnt return all userinfo

### ISSUE THREAD

**Issue by CruzST** [domdom258/CS467_project#23]
upon logging in and navigating to account page
![image](https://user-images.githubusercontent.com/30658915/59154177-50cf2600-8a3a-11e9-8659-1e131f876fc0.png)

after hard refresh on account page
![image](https://user-images.githubusercontent.com/30658915/59154181-6f352180-8a3a-11e9-8eb9-4988333149f7.png)

**Comment by CruzST** [comment]
it might have something to do with nextTick?
https://vuejsdevelopers.com/2019/01/22/vue-what-is-next-tick/

I've been using that in my other components since it was prevalent in the documentation for created/mounted.  Also maybe is should be in an updated lifecycle hook as well as created?

**Comment by michelle-tan** [comment]
Did you find that the latest pull request solves this problem? I am no longer having issues with it, let me know if you do though

**Comment by CruzST** [comment]
Same here, thanks!
